### ISSUE TITLE
traverse is not a function

### ISSUE THREAD

**Issue by motiapp** [cawa-93/unplugin-auto-expose#18]
I am trying to use this updated (0.2.x) package in my electron app, which is based on your vite-electron-builder boilerplate. It was working well in the previous version (0.0.5), but now when running the app in dev mode (npm run watch) I get an error in the console:

**[unplugin-auto-expose-preload] traverse is not a function**

and the app fails to render anything on launch. I'm running on Node 20.11 with Typescript 5.3.3 and Vite 5.0.12.

This seems to be a CommonJS/ESM issue, as I can fix it by hacking the index.mjs file and change:

`32:  import traverse from "@babel/traverse";`

to:

`32: import $traverse from "@babel/traverse";`
`33: const traverse = $traverse.default;`

As this is more of a problem with ESM & CommonJS mixing together, I figured that changing settings in tsconfig.json would help (like adding **allowSyntheticDefaultImports: true** and **esModuleInterop: true**), but it didn't.

I'm wondering if you have any insight into how to fix this problem I'm sure you know all about the pain of mixing CJS & ESM in an Electron project.

**Comment by cawa-93** [comment]
Will it work if you tried something like this
```js
import * as traverse from "@babel/traverse";
```
or
```js
import {default as traverse} from "@babel/traverse";
```

**Comment by motiapp** [comment]
No, neither of those work for me.

**Comment by motiapp** [comment]
For additional context there's this (although it's 2+ years old now):
https://github.com/babel/babel/issues/13855

**Comment by cawa-93** [comment]
Should be [fixed](https://github.com/cawa-93/unplugin-auto-expose/commit/125c9e8271eb282872c8a0a3a1384ce05be6b2ef) in v0.2.4

**Comment by cawa-93** [comment]
Fixed in v0.3
